# Icon Theme Profile

# The FreeDesktop Suru icon set is designed and developed by:
# - Sam Hewitt <sam@snwh.org>
# - under GPL3

# The original Suru icon set and concept was created by:
# - Matthieu James
# - Canonical Design Team

# Core developers (in order of appearance):
# - Andrea Bonanni (original author) <bonandry@gmail.com>
# - Gustavo Costa <gusbemacbe@gmail.com>

# * Devices icons are inspired by La Capitaine created by:
# - Keefer Rourke <mail@krourke.org>
# - under GPL3/MIT

# * Emoji icons are derived from the Twenoji created by:
# - Twitter Team
# - under MIT

# * Mimetype icons are based on Numix mimetypes icons created by:
# - Numix Team
# - under GPL3

# * Devices and places icons and several apps icons are inspired by Papirus icons created by:
# - Alexey Varfolomeev <https://github.com/varlesh>
# - under GPL3

# * Numberless icons are from Gravit Designer, under GPL3/MIT

# Using most icons from this package https://www.opencode.net/adhe/gruvboxplasma

# The packages above it are mainly for places. 


[Icon Theme]
Name=Gruvbox
Comment=Gruvbox, modern and colorful icon theme

#
Inherits=Papirus,breeze,Numix

Example=folder

FollowsColorScheme=true


# Directory list
Directories=16/devices,16/emblems,16/mimetypes,16/apps,16/places,32/mimetypes,32/places,48/apps,48/mimetypes,48/places,64/devices,64/mimetypes,64/places

#--------------------

[16/places]
Context=Places
Size=16
MinSize=8
MaxSize=22
Type=Scalable


[16/mimetypes]
Context=MimeTypes
Size=16
MinSize=16
MaxSize=22
Type=Scalable

[16/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=22
Type=Scalable


[16/emblems]
Context=Emblems
Size=16
MinSize=8
MaxSize=22
Type=Scalable

[16/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=22
Type=Scalable

#--------------------

[32/places]
Context=Places
Size=32
MinSize=32
MaxSize=32
Type=Fixed

[32/mimetypes]
Context=MimeTypes
Size=32
MinSize=32
MaxSize=32
Type=Fixed

#--------------------

[48/places]
Context=Places
Size=48
MinSize=48
MaxSize=48
Type=Fixed

[48/mimetypes]
Context=MimeTypes
Size=48
MinSize=48
MaxSize=48
Type=Fixed

[48/apps]
Context=Applications
Size=48
MinSize=32
MaxSize=512
Type=Scalable

#--------------------

[64/places]
Context=Places
Size=64
MinSize=64
MaxSize=512
Type=Scalable

[64/mimetypes]
Context=MimeTypes
Size=64
MinSize=64
MaxSize=512
Type=Scalable
